apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-microservice
  template:
    metadata:
      labels:
        app: devops-microservice
    spec:
      containers:
        - name: devops-microservice
          image: devops-microservice:latest
          ports:
            - containerPort: 8000 