apiVersion: v1
kind: Service
metadata:
  name: devops-microservice
spec:
  type: NodePort
  selector:
    app: devops-microservice
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080 