name: CI

on:
  push:
    branches: ["main", "master", "develop", "feature/**"]
  pull_request:
    branches: ["*"]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          flake8 app tests --max-line-length=120 --ignore=E203,W503

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/devops-microservice:latest .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/devops-microservice:latest ${{ secrets.DOCKERHUB_USERNAME }}/devops-microservice:${{ github.sha }}

  deploy:
    needs: build-test-lint
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/devops-microservice:latest .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/devops-microservice:latest ${{ secrets.DOCKERHUB_USERNAME }}/devops-microservice:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/devops-microservice:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/devops-microservice:${{ github.sha }} 